### ISSUE TITLE
Doesn't work with all/currently watching/completed/etc anime list

### ISSUE THREAD

**Issue by Euphoreka7** [HritikVaishnav/Myanimelist-Redesigned#1]
https://myanimelist.net/animelist/Euphoreka7?status=1 (or any other tab) gives me original style with plugin enabled

**Comment by HritikVaishnav** [comment]
Actually, I have deliberately left the AnimeList & MangaList pages out because people usually customize those pages themselves, and thus the extension's own CSS and JS customizations can cause problems.
