### ISSUE TITLE
"Write a review" button not appearing

### ISSUE THREAD

**Issue by AsuxAX** [HritikVaishnav/Myanimelist-Redesigned#12]
Hi,
I was trying to review a manga I just read however did not seem to find the "write a review" button.
Got curious and turned off the extension, then it showed up.
I believe that this is a mistake in the extension.

Theme: Blackpearl

**Comment by HritikVaishnav** [comment]
it's been long since the last update. Have to fix quite a lot.
Will try to do it before the weekend

**Comment by AsuxAX** [comment]
> it's been long since the last update. Have to fix quite a lot. Will try to do it before the weekend

Ok thanks.

**Comment by HritikVaishnav** [comment]
Hey, I have updated the extension. 
The btn should be visible now, can you check and let me know?

**Comment by AsuxAX** [comment]
> Hey, I have updated the extension. The btn should be visible now, can you check and let me know?

Yes, thanks, it works.
Sorry for the late response btw.
