### ISSUE TITLE
"Recently Updated By" no longer showing up on anime page

### ISSUE THREAD

**Issue by Powish** [HritikVaishnav/Myanimelist-Redesigned#13]
"Recently Updated By" section on anime page that shows friend's scores is missing when using the redesign, even though it was there before.

With extension turned off
![image](https://user-images.githubusercontent.com/80339945/181624390-fb343366-cf92-4329-8d8a-1a6337f26345.png)
With extention turned on
![image](https://user-images.githubusercontent.com/80339945/181624523-30b9474f-2d3f-4022-83b0-93928be6e052.png)

**Comment by HritikVaishnav** [comment]
Hey, I have updated the extension. 
Can you check if the issue still exists or not?

**Comment by Powish** [comment]
It works now. Thanks.
