### ISSUE TITLE
Dark mode not working properly in forums

### ISSUE THREAD

**Issue by musubi3** [HritikVaishnav/Myanimelist-Redesigned#16]
Post in forums appear with a white background and light text making them illegible while in dark mode.

![MAL Forums Screenshot](https://user-images.githubusercontent.com/71198693/197084430-76022781-7f00-4d10-95c8-bbc70832ee93.png)

**Comment by shatterstar13** [comment]
Been having the same issue

![Screenshot (76)](https://user-images.githubusercontent.com/105117729/197370143-0010605d-96ab-4387-98a7-8d4e2f856b61.png)

**Comment by Goku-04** [comment]
Weird that it got fixed by itself lol
![image](https://user-images.githubusercontent.com/65329453/201102790-737459fd-6046-4e0e-9fe4-235aefce74c1.png)

**Comment by shatterstar13** [comment]
Yeah weird
