### ISSUE TITLE
[Bug] Extension breaks when MAL's built-in dark mode is enabled.

### ISSUE THREAD

**Issue by Asudox** [HritikVaishnav/Myanimelist-Redesigned#24]

**Comment by ruxunderscore** [comment]
The Navigation Bar takes up more space at the top and covers a good portion of the content below it. Disabling dark mode in MAL's settings fixes this.

**Comment by Laesx** [comment]
Recently even with dark mode disabled seems like there are some slight css problems still, the top menu bar is bugging a bit and some colors/boxes are a bit off on anime pages for example.

**Comment by HritikVaishnav** [comment]
I just pushed a fix for it.
The release is under review so may take a day before the release.
