### ISSUE TITLE
Profile Settings 

### ISSUE THREAD

**Issue by Goku-04** [HritikVaishnav/Myanimelist-Redesigned#3]
When editing the **About Me** section the previous BBCode _disappears_ with the extension toggled on and becomes _visible_ on toggling it off

![image](https://user-images.githubusercontent.com/65329453/148245106-501279c3-8579-4e01-b5ec-bfcf556c4a3e.png)
![image](https://user-images.githubusercontent.com/65329453/148245122-79f285ca-80d6-4a06-9516-9cd5739159b7.png)

**Comment by HritikVaishnav** [comment]
Thank you for reporting, will fit it soon.

**Comment by HritikVaishnav** [comment]
is it fixed?

**Comment by Goku-04** [comment]
Yes...thanks for this beautiful extension
