### ISSUE TITLE
Seasonal anime view (https://myanimelist.net/anime/season) shows some per title info in a white box even though im using the dark theme, and this get quite distracting

### ISSUE THREAD

**Issue by GitExploraa** [HritikVaishnav/Myanimelist-Redesigned#4]

**Comment by HritikVaishnav** [comment]
I see, Seems like Mal made some updates recently. Will update it tonight.

**Comment by GitExploraa** [comment]
noted, thank you

**Comment by HritikVaishnav** [comment]
welcome :) 
keep reporting the bugs you encounter, there are some I am aware of but there are many I have no idea about.

**Comment by GitExploraa** [comment]
no problem, i'll gladly do that if i encounter any
