### ISSUE TITLE
Character and Staff panels get cut out now.

### ISSUE THREAD

**Issue by Laesx** [HritikVaishnav/Myanimelist-Redesigned#5]
Apparently MAL has recently updated some aspects of their site and now basically the whole anime page gets cut a bit in the right side.

![firefox_vOqVC89MIb](https://user-images.githubusercontent.com/51269470/154867737-4965fcc4-29d1-4f9e-bd54-2c0ab9741605.png)

They also changed their studio details page and it's completely broken as well.

![imagen](https://user-images.githubusercontent.com/51269470/154867809-9ffdf749-e46d-4a3a-93c8-ac6727eafbb8.png)

Seems like this project is dead but please I hope you can look into this.

**Comment by Laesx** [comment]
I'm sorry I didn't see that the extension had been updated but on a different extension on the firefox store, pardon this.

**Comment by HritikVaishnav** [comment]
I lost the previous Mozilla account's 2FA thus had to upload the new versions on a new account.
