### ISSUE TITLE
Studio page looks odd

### ISSUE THREAD

**Issue by Laesx** [HritikVaishnav/Myanimelist-Redesigned#6]
This is the default view now (apparently changed recently). The covers look too small and the text and buttons are in odd positions.
The selector for TV/ONA/Movie too looks out of place

![Screenshot 2022-03-01 at 19-32-21  CloverWorks - Anime Producer - MyAnimeList net ](https://user-images.githubusercontent.com/51269470/156228030-20141bbd-2743-4660-bdec-43a7d2b466fc.png)

**Comment by HritikVaishnav** [comment]
working on it.
