### ISSUE TITLE
Almost everything white regardless of theme only if uBlock Origin is activated

### ISSUE THREAD

**Issue by Laesx** [HritikVaishnav/Myanimelist-Redesigned#8]
You must've noticed but seems MAL did some breaking changes a few hours ago, breaks even with dark reader.

![imagen](https://user-images.githubusercontent.com/51269470/162854183-f67d8eba-1516-46b1-977a-8767851f9ab9.png)
![imagen](https://user-images.githubusercontent.com/51269470/162854211-862a25d5-24d3-4782-9abd-9cfd049a93b0.png)

I have confirmed this only happens if uBlock Origin is activated, just turn off for MAL and fixed, not that big of a deal, since you can block ads with your extension as well, leaving this here if you want to check it out or if any other user wants to know why it happened.

**Comment by HritikVaishnav** [comment]
Hi, I tried to replicate the issue. But wasn't able to. 
I also use uBlock-Origin but no issue for me.
Can you share a screenshot of your browser console?

**Comment by Laesx** [comment]
Seems it doesn't happen anymore and they reverted whatever change they did, welp, gonna wait a few days before bug report
