### ISSUE TITLE
UBlock messes with the theming

### ISSUE THREAD

**Issue by Goku-04** [HritikVaishnav/Myanimelist-Redesigned#9]
Recently UBlock started blocking some css because of which the theme looks like this
![image](https://user-images.githubusercontent.com/65329453/164611305-7e2591e3-7b59-4dc6-a7ca-69de0ff9413f.png)
 
Any way to sort this out?

**Comment by nuxencs** [comment]
Disabling Cosmetic Filtering for MAL in uBlock will fix this until Hritik pushes a fix.
You can do that like this:
![J3I1TEA4CQ](https://user-images.githubusercontent.com/47067662/164707258-98aab4b0-7af9-4c11-aab8-1fe7520179af.png)

**Comment by Goku-04** [comment]
Thanks for the method....it works. 
I will keep the issue open till it gets fixed
